export type MoneyValue=number|bigint|{toString():string};
export type ReceivablePayment={amount:MoneyValue;receivableScheduleId?:string|null;paymentDate?:Date;deletedAt?:Date|null};
export type ReceivableScheduleValue={id:string;expectedAmount:MoneyValue;dueType:"DATE"|"NEGOTIATION";dueDate?:Date|null;taxInvoiceIssued?:boolean;deletedAt?:Date|null;payments?:ReceivablePayment[]};
const money=(value:MoneyValue)=>{const result=Number(value);if(!Number.isSafeInteger(result))throw new RangeError("금액은 안전한 원 단위 정수여야 합니다.");return result};
export function calculateScheduleBalance(schedule:ReceivableScheduleValue,payments:ReceivablePayment[]=schedule.payments??[]){const paid=payments.filter(p=>!p.deletedAt&&p.receivableScheduleId===schedule.id).reduce((sum,p)=>sum+money(p.amount),0);return{paidAmount:paid,balance:Math.max(0,money(schedule.expectedAmount)-paid),overpaidAmount:Math.max(0,paid-money(schedule.expectedAmount))}}
export function calculateOverdueDays(dueDate:Date|null|undefined,now=new Date()){if(!dueDate)return 0;const due=Date.UTC(dueDate.getUTCFullYear(),dueDate.getUTCMonth(),dueDate.getUTCDate()),today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());return Math.max(0,Math.floor((today-due)/86400000))}
export function calculateCollectionRate(contractAmount:MoneyValue,receivedAmount:MoneyValue){const contract=money(contractAmount);return contract===0?0:money(receivedAmount)*100/contract}
export type ReceivableStatus="UNPLANNED"|"EXPECTED"|"PARTIAL"|"COMPLETE"|"OVERDUE"|"OVERPAID";
export function calculateReceivableStatus(input:{contractAmount:MoneyValue;receivedAmount:MoneyValue;overdueAmount:MoneyValue;scheduleCount:number}):ReceivableStatus{const contract=money(input.contractAmount),received=money(input.receivedAmount),overdue=money(input.overdueAmount);if(received>contract)return"OVERPAID";if(received>=contract&&contract>=0)return"COMPLETE";if(overdue>0)return"OVERDUE";if(received>0)return"PARTIAL";if(input.scheduleCount>0)return"EXPECTED";return"UNPLANNED"}
export function calculateProjectReceivable(contractAmount:MoneyValue,schedules:ReceivableScheduleValue[],payments:ReceivablePayment[],now=new Date()){const validPayments=payments.filter(p=>!p.deletedAt),validSchedules=schedules.filter(s=>!s.deletedAt),receivedAmount=validPayments.reduce((sum,p)=>sum+money(p.amount),0),scheduleTotal=validSchedules.reduce((sum,s)=>sum+money(s.expectedAmount),0);let overdueAmount=0,upcomingAmount=0,negotiationAmount=0;for(const schedule of validSchedules){const balance=calculateScheduleBalance(schedule,validPayments).balance;if(schedule.dueType==="NEGOTIATION")negotiationAmount+=balance;else if(schedule.dueDate&&schedule.dueDate<now)overdueAmount+=balance;else upcomingAmount+=balance}const contract=money(contractAmount),receivableAmount=Math.max(0,contract-receivedAmount),overpaidAmount=Math.max(0,receivedAmount-contract),unassignedAmount=validPayments.filter(p=>!p.receivableScheduleId).reduce((s,p)=>s+money(p.amount),0);return{contractAmount:contract,scheduleTotal,receivedAmount,receivableAmount,overpaidAmount,overdueAmount,upcomingAmount,negotiationAmount,unassignedAmount,unplannedAmount:contract-scheduleTotal,collectionRate:calculateCollectionRate(contract,receivedAmount),status:calculateReceivableStatus({contractAmount:contract,receivedAmount,overdueAmount,scheduleCount:validSchedules.length})}}
export type AgingBucket="UPCOMING"|"OVERDUE_1_30"|"OVERDUE_31_60"|"OVERDUE_61_90"|"OVERDUE_91_PLUS"|"NEGOTIATION";
export function calculateReceivableAging(schedules:ReceivableScheduleValue[],payments:ReceivablePayment[],now=new Date()){const result:Record<AgingBucket,{count:number;amount:number}>={UPCOMING:{count:0,amount:0},OVERDUE_1_30:{count:0,amount:0},OVERDUE_31_60:{count:0,amount:0},OVERDUE_61_90:{count:0,amount:0},OVERDUE_91_PLUS:{count:0,amount:0},NEGOTIATION:{count:0,amount:0}};for(const s of schedules.filter(x=>!x.deletedAt)){const balance=calculateScheduleBalance(s,payments).balance;if(balance<=0)continue;let key:AgingBucket;if(s.dueType==="NEGOTIATION")key="NEGOTIATION";else{const days=calculateOverdueDays(s.dueDate,now);key=days===0?"UPCOMING":days<=30?"OVERDUE_1_30":days<=60?"OVERDUE_31_60":days<=90?"OVERDUE_61_90":"OVERDUE_91_PLUS"}result[key].count++;result[key].amount+=balance}return result}
