import type { ProjectStatus } from "@prisma/client";
import Link from "next/link";
import { card, Empty, input, Notice, PageHeader } from "@/components/common/page";
import { projectStatusLabels } from "@/features/project-costs/labels";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const query = await searchParams;
  const projects = await db.project.findMany({ where: { deletedAt: null, ...(query.status ? { status: query.status as ProjectStatus } : {}), ...(query.search ? { OR: [{ projectCode: { contains: query.search } }, { projectName: { contains: query.search } }, { client: { companyName: { contains: query.search } } }, { quotation: { quotationNumber: { contains: query.search } } }] } : {}) }, include: { client: true, manager: true, quotation: true, expenses: { where: { deletedAt: null, status: { notIn: ["REJECTED", "CANCELED"] } } }, purchaseOrders: { where: { deletedAt: null, status: { not: "CANCELED" } } }, purchaseDisbursements: { where: { deletedAt: null, status: "EXECUTED" } }, payments: { where: { deletedAt: null } } }, orderBy: { updatedAt: "desc" } });
  return <div className="p-8"><PageHeader title="프로젝트 중심 관리" description="견적서에서 시작한 오더·구매·비용·수금 흐름을 통합 관리합니다." /><Notice success={query.success} error={query.error} /><div className="mt-4 rounded-lg border bg-blue-50 p-4 text-sm">새 프로젝트는 견적서 상세에서 발행 확정 후 등록합니다. <Link className="ml-2 font-semibold text-blue-700" href="/quotations?issued=1">견적서에서 프로젝트 등록</Link></div><form className={`${card} mt-4 grid grid-cols-4 gap-3 p-4`}><input className={`${input} col-span-2 mt-0`} defaultValue={query.search} name="search" placeholder="프로젝트·견적번호·거래처 검색" /><select className={`${input} mt-0`} defaultValue={query.status} name="status"><option value="">전체 상태</option>{Object.entries(projectStatusLabels).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select><button className="rounded border">조회</button></form><div className={`${card} mt-4 overflow-x-auto`}>{!projects.length ? <Empty /> : <table className="min-w-[1600px] w-full text-sm"><thead><tr>{["프로젝트번호", "프로젝트명", "거래처", "원본 견적번호", "견적금액", "담당자", "진행상태", "구매발주액", "실제 집행비용", "예상이익", "입금액", "미수금"].map((heading) => <th className="p-3 text-left" key={heading}>{heading}</th>)}</tr></thead><tbody>{projects.map((project) => { const contract = Number(project.contractSupplyAmount) || Number(project.contractAmount), purchase = project.purchaseOrders.reduce((sum, order) => sum + Number(order.subtotal), 0), actual = project.expenses.reduce((sum, expense) => sum + Number(expense.supplyAmount), 0), received = project.payments.reduce((sum, payment) => sum + Number(payment.amount), 0); return <tr className="border-t" key={project.id}><td className="p-3">{project.projectCode}</td><td><Link className="font-semibold text-blue-700" href={`/project-costs/${project.id}`}>{project.projectName}</Link></td><td>{project.client.companyName}</td><td>{project.quotation ? `${project.quotation.quotationNumber} Rev.${project.quotation.revision}` : "Legacy Project"}</td><td className="text-right">{won(contract)}</td><td>{project.manager.name}</td><td>{projectStatusLabels[project.status]}</td><td className="text-right">{won(purchase)}</td><td className="text-right">{won(actual)}</td><td className={`text-right ${contract - actual < 0 ? "text-red-600" : ""}`}>{won(contract - actual)}</td><td className="text-right">{won(received)}</td><td className="text-right">{won(Math.max(0, (Number(project.contractTotalAmount) || Number(project.contractAmount)) - received))}</td></tr>; })}</tbody></table>}</div></div>;
}
