import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { card, Empty, Notice, PageHeader } from "@/components/common/page";
import { DocumentFlow } from "@/components/common/document-flow";
import { completeProject } from "@/features/project-costs/actions";
import { calculateProjectCostSummary } from "@/features/project-costs/calculations";
import { projectStatusLabels } from "@/features/project-costs/labels";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;
const date = (value: Date | null | undefined) => value?.toISOString().slice(0, 10) ?? "-";

export default async function Page({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const { projectId } = await params, query = await searchParams, tab = query.tab ?? "summary";
  const project = await db.project.findFirst({ where: { id: projectId, deletedAt: null }, include: { client: true, manager: true, quotation: { include: { issuedBy: true } }, budgets: { include: { expenseCategory: true } }, expenses: { where: { deletedAt: null }, include: { expenseCategory: true, supplier: true, purchaseDisbursement: true }, orderBy: { expenseDate: "desc" } }, orders: { where: { deletedAt: null }, include: { workflowTemplate: true }, orderBy: { createdAt: "desc" } }, purchaseRfqs: { where: { deletedAt: null }, include: { supplierQuotations: { where: { deletedAt: null }, include: { supplier: true } } }, orderBy: { requestDate: "desc" } }, purchaseOrders: { where: { deletedAt: null }, include: { supplier: true, items: { include: { receiptItems: { where: { goodsReceipt: { deletedAt: null, status: { not: "CANCELED" } } } } } }, receipts: { where: { deletedAt: null, status: { not: "CANCELED" } } }, disbursements: { where: { deletedAt: null } } }, orderBy: { orderDate: "desc" } }, purchaseDisbursements: { where: { deletedAt: null }, include: { supplier: true, purchaseOrder: true }, orderBy: { createdAt: "desc" } }, statements: { where: { deletedAt: null }, orderBy: { statementDate: "desc" } }, payments: { where: { deletedAt: null }, orderBy: { paymentDate: "desc" } }, receivableSchedules: { where: { deletedAt: null }, orderBy: { sequence: "asc" } }, scheduleEvents: { where: { deletedAt: null }, orderBy: { startAt: "asc" } } } });
  if (!project) notFound();
  const contractSupply = Number(project.contractSupplyAmount) || Number(project.contractAmount), contractTotal = Number(project.contractTotalAmount) || Number(project.contractAmount);
  const activeExpenses = project.expenses.filter((expense) => !["REJECTED", "CANCELED"].includes(expense.status)), summary = calculateProjectCostSummary(contractSupply, Number(project.budgetAmount), activeExpenses), purchaseAmount = project.purchaseOrders.filter((order) => order.status !== "CANCELED").reduce((sum, order) => sum + Number(order.subtotal), 0), executed = project.purchaseDisbursements.filter((payment) => payment.status === "EXECUTED").reduce((sum, payment) => sum + Number(payment.totalAmount), 0), received = project.payments.reduce((sum, payment) => sum + Number(payment.amount), 0), receivable = Math.max(0, contractTotal - received);
  const flow = [...(project.quotation ? [{ type: "QUOTATION", id: project.quotation.id, number: `${project.quotation.quotationNumber} Rev.${project.quotation.revision}`, label: "견적서", href: `/quotations/${project.quotation.id}` }] : []), { type: "PROJECT", id: project.id, number: project.projectCode, label: "프로젝트", href: `/project-costs/${project.id}` }, ...project.orders.map((order) => ({ type: "ORDER", id: order.id, number: order.orderNumber, label: "오더", href: `/orders/${order.id}` })), ...project.purchaseRfqs.map((rfq) => ({ type: "PURCHASE_RFQ", id: rfq.id, number: rfq.rfqNumber, label: "견적요청", href: `/procurement/rfqs/${rfq.id}` })), ...project.purchaseOrders.map((order) => ({ type: "PURCHASE_ORDER", id: order.id, number: order.purchaseOrderNumber, label: "구매 발주서", href: `/procurement/purchase-orders/${order.id}` })), ...project.statements.map((statement) => ({ type: "STATEMENT", id: statement.id, number: statement.statementNumber, label: "거래명세서", href: `/transaction-statements/${statement.id}` }))];
  const cards: Array<[string, string]> = [["프로젝트번호", project.projectCode], ["진행상태", projectStatusLabels[project.status]], ["계약 공급가액", won(contractSupply)], ["계약 부가세", won(Number(project.contractVatAmount))], ["계약 총액", won(contractTotal)], ["예산", won(Number(project.budgetAmount))], ["구매발주액", won(purchaseAmount)], ["실제 원가", won(summary.actualCost)], ["실제 지급액", won(executed)], ["예상이익", won(contractSupply - summary.actualCost)], ["입금액", won(received)], ["미수금", won(receivable)], ["진행률", `${Number(project.progressRate).toFixed(1)}%`]];
  return <div className="p-8"><PageHeader title={project.projectName} description={`${project.projectCode} · ${project.client.companyName}`} /><Notice success={query.success} error={query.error} /><DocumentFlow nodes={flow} currentId={project.id} /><div className="mt-4 flex gap-2"><Link className="rounded bg-blue-600 px-4 py-2 text-white" href={`/orders/new?quotationId=${project.quotationId ?? ""}&projectId=${project.id}`}>오더 생성</Link><Link className="rounded border px-4 py-2" href={`/procurement/rfqs/new?projectId=${project.id}&quotationId=${project.quotationId ?? ""}`}>구매 견적요청 생성</Link><Link className="rounded border px-4 py-2" href={`/project-costs/${project.id}/expenses/new`}>비용 등록</Link><Link className="rounded border px-4 py-2" href={`/project-costs/${project.id}/budget`}>예산 편집</Link><Link className="rounded border px-4 py-2" href={`/project-costs/${project.id}/edit`}>프로젝트 수정</Link>{!["COMPLETED","SETTLING","CLOSED","CANCELED"].includes(project.status)&&<form action={completeProject} className="flex items-center gap-2"><input type="hidden" name="projectId" value={project.id}/><label className="text-xs"><input required type="checkbox" name="confirm"/> 완료 조건 확인</label><button className="rounded border border-green-600 px-4 py-2 text-green-700">프로젝트 완료</button></form>}</div><nav className="mt-6 flex flex-wrap border-b">{[["summary", "요약"], ["quotation", "견적서"], ["orders", "오더"], ["procurement", "구매/발주"], ["costs", "비용집행"], ["statements", "거래명세서"], ["receivables", "입금/미수금"], ["schedule", "일정"]].map(([value, name]) => <Link className={`px-4 py-3 text-sm ${tab === value ? "border-b-2 border-blue-600 font-bold text-blue-700" : ""}`} href={`/project-costs/${project.id}?tab=${value}`} key={value}>{name}</Link>)}</nav>
    {tab === "summary" && <section className="mt-4 grid grid-cols-4 gap-3">{cards.map(([name, value]) => <div className={`${card} p-4`} key={name}><p className="text-xs text-slate-500">{name}</p><b className="mt-1 block text-lg">{value}</b></div>)}</section>}
    {tab === "quotation" && <section className={`${card} mt-4 p-5`}>{project.quotation ? <><div className="grid grid-cols-6 gap-4 text-sm"><p>견적번호 <b>{project.quotation.quotationNumber}</b></p><p>Revision <b>{project.quotation.revision}</b></p><p>견적일 <b>{date(project.quotation.quotationDate)}</b></p><p>발행일 <b>{date(project.quotation.issuedAt)}</b></p><p>공급가액 <b>{won(Number(project.quotation.taxableAmount))}</b></p><p>총액 <b>{won(Number(project.quotation.totalAmount))}</b></p></div><div className="mt-4 flex gap-2"><Link className="rounded border px-3 py-2" href={`/quotations/${project.quotation.id}`}>상세보기</Link><Link className="rounded border px-3 py-2" href={`/quotations/${project.quotation.id}/print`}>PDF/인쇄</Link><a className="rounded border px-3 py-2" href={`/api/quotations/${project.quotation.id}/excel`}>Excel</a></div></> : <p>견적서가 없는 기존 Legacy Project입니다.</p>}</section>}
    {tab === "orders" && <Table headers={["오더번호", "오더명", "업무 흐름", "상태", "진행률"]} rows={project.orders.map((order) => [<Link className="text-blue-700" href={`/orders/${order.id}`} key={order.id}>{order.orderNumber}</Link>, order.orderName, order.workflowTemplate.name, order.status, `${Number(order.progressRate).toFixed(0)}%`])} />}
    {tab === "procurement" && <div className="space-y-4"><Table title="견적요청" headers={["RFQ 번호", "요청일", "상태", "업체 견적 수"]} rows={project.purchaseRfqs.map((rfq) => [<Link className="text-blue-700" href={`/procurement/rfqs/${rfq.id}`} key={rfq.id}>{rfq.rfqNumber}</Link>, date(rfq.requestDate), rfq.status, rfq.supplierQuotations.length])} /><Table title="공급업체 견적" headers={["공급업체", "업체견적번호", "견적금액", "선정 여부"]} rows={project.purchaseRfqs.flatMap((rfq) => rfq.supplierQuotations.map((quote) => [quote.supplier.companyName, <Link className="text-blue-700" href={`/procurement/supplier-quotations/${quote.id}`} key={quote.id}>{quote.supplierQuotationNumber}</Link>, won(Number(quote.totalAmount)), ["SELECTED", "PARTIALLY_SELECTED"].includes(quote.status) ? "선정" : "-"]))} /><Table title="구매 발주서" headers={["발주번호", "공급업체", "발주일", "발주금액", "입고율", "지급액", "미지급액"]} rows={project.purchaseOrders.map((order) => { const ordered = order.items.reduce((sum, item) => sum + Number(item.orderedQuantity), 0), receivedQuantity = order.items.flatMap((item) => item.receiptItems).reduce((sum, item) => sum + Number(item.receivedQuantity), 0), paid = order.disbursements.filter((payment) => payment.status === "EXECUTED").reduce((sum, payment) => sum + Number(payment.totalAmount), 0); return [<Link className="text-blue-700" href={`/procurement/purchase-orders/${order.id}`} key={order.id}>{order.purchaseOrderNumber}</Link>, order.supplier.companyName, date(order.orderDate), won(Number(order.totalAmount)), `${ordered ? Math.min(100, receivedQuantity / ordered * 100).toFixed(0) : 0}%`, won(paid), won(Number(order.totalAmount) - paid)]; })} /><Table title="입고" headers={["입고번호", "구매 발주서", "입고일", "입고상태"]} rows={project.purchaseOrders.flatMap((order) => order.receipts.map((receipt) => [<Link className="text-blue-700" href={`/procurement/goods-receipts/${receipt.id}`} key={receipt.id}>{receipt.goodsReceiptNumber}</Link>, order.purchaseOrderNumber, date(receipt.receiptDate), receipt.status]))} /><Table title="대금집행" headers={["집행번호", "공급업체", "구매 발주서", "계획금액", "집행금액", "상태", "집행일"]} rows={project.purchaseDisbursements.map((payment) => [<Link className="text-blue-700" href={`/procurement/disbursements/${payment.id}`} key={payment.id}>{payment.disbursementNumber}</Link>, payment.supplier.companyName, payment.purchaseOrder.purchaseOrderNumber, won(Number(payment.totalAmount)), payment.status === "EXECUTED" ? won(Number(payment.totalAmount)) : won(0), payment.status, date(payment.executedDate)])} /></div>}
    {tab === "costs" && <Table headers={["비용번호", "일자", "구분", "지급처", "비용명", "공급가액", "상태", "출처"]} rows={project.expenses.map((expense) => [<Link className="text-blue-700" href={`/project-costs/${project.id}/expenses/${expense.id}`} key={expense.id}>{expense.expenseNumber}</Link>, date(expense.expenseDate), expense.expenseCategory.name, expense.supplier?.companyName ?? expense.supplierName ?? "-", expense.description, won(Number(expense.supplyAmount)), expense.status, expense.purchaseDisbursement ? "구매 대금집행" : "직접 등록"])} />}
    {tab === "statements" && <Table headers={["거래명세서", "일자", "제목", "금액", "상태", "출력"]} rows={project.statements.map((statement) => [<Link className="text-blue-700" href={`/transaction-statements/${statement.id}`} key={statement.id}>{statement.statementNumber}</Link>, date(statement.statementDate), statement.title, won(Number(statement.totalAmount)), statement.status, <Link href={`/transaction-statements/${statement.id}/print`} key={`p-${statement.id}`}>PDF/인쇄</Link>])} />}
    {tab === "receivables" && <><div className="mt-4 grid grid-cols-3 gap-3"><Metric name="계약 총액" value={won(contractTotal)} /><Metric name="입금액" value={won(received)} /><Metric name="미수금" value={won(receivable)} /></div><Table headers={["입금번호", "입금일", "구분", "금액"]} rows={project.payments.map((payment) => [payment.paymentNumber, date(payment.paymentDate), payment.paymentType, won(Number(payment.amount))])} /></>}
    {tab === "schedule" && <Table headers={["일정", "시작", "종료", "상태"]} rows={project.scheduleEvents.map((event) => [event.title, date(event.startAt), date(event.endAt), event.category])} />}
  </div>;
}

function Metric({ name, value }: { name: string; value: string }) { return <div className={`${card} p-4`}><p className="text-xs text-slate-500">{name}</p><b className="text-xl">{value}</b></div>; }
function Table({ title, headers, rows }: { title?: string; headers: string[]; rows: Array<Array<ReactNode>> }) { return <section className={`${card} mt-4 overflow-x-auto`}>{title && <h3 className="p-4 font-bold">{title}</h3>}{!rows.length ? <Empty /> : <table className="w-full text-sm"><thead><tr>{headers.map((header) => <th className="p-3 text-left" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t" key={index}>{row.map((value, cell) => <td className="p-3" key={cell}>{value}</td>)}</tr>)}</tbody></table>}</section>; }
