import { notFound } from "next/navigation";
import Link from "next/link";
import { Notice, PageHeader } from "@/components/common/page";
import { QuotationStatusBadge } from "@/components/common/quotation-status-badge";
import { QuotationForm, type QuotationFormValue } from "@/components/forms/quotation-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { createQuotationRevision, deleteQuotation } from "@/features/quotations/actions";
import { createStatementFromQuotation } from "@/features/transaction-statements/actions";
import { db } from "@/lib/db";
import { calculateConstructionQuotationTotals } from "@/lib/construction-quotation";
const date = (value: Date | null) => value ? value.toISOString().slice(0, 10) : "";
export default async function QuotationDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params, query = await searchParams; const [quotation, clients, products, suppliers] = await Promise.all([db.quotation.findFirst({ where: { id, deletedAt: null }, include: { items: { orderBy: { sortOrder: "asc" } } } }), db.client.findMany({ where: { deletedAt: null }, select: { id: true, companyName: true }, orderBy: { companyName: "asc" } }), db.product.findMany({ where: { deletedAt: null, isActive: true }, orderBy: { name: "asc" } }), db.supplierProfile.findMany({where:{deletedAt:null,isActive:true},orderBy:[{isDefault:"desc"},{profileName:"asc"}]})]); if (!quotation) notFound();
  const recalculated=calculateConstructionQuotationTotals(quotation.items.map(item=>({costCategory:item.costCategory,quantity:item.quantity.toString(),unitPrice:item.unitPrice.toString(),discountRate:item.discountRate.toString()})),{toolLossRate:quotation.toolLossRate.toString(),generalAdminRate:quotation.generalAdminRate.toString(),safetyHealthRate:quotation.safetyHealthRate.toString()}); const needsRecalculation=recalculated.totalAmount!==BigInt(quotation.totalAmount.toFixed(0));
  const initial: QuotationFormValue = { id: quotation.id, supplierProfileId: quotation.supplierProfileId ?? "", showSupplierLogo: quotation.showSupplierLogo, showSupplierSeal: quotation.showSupplierSeal, clientId: quotation.clientId, projectName: quotation.projectName, title: quotation.title, quotationDate: date(quotation.quotationDate), validUntil: date(quotation.validUntil), deliveryDeadlineType: quotation.deliveryDeadlineType, deliveryDeadlineDate: date(quotation.deliveryDeadlineDate), paymentTerms: quotation.paymentTerms ?? "", deliveryTerms: quotation.deliveryTerms ?? "", note: quotation.note ?? "", status: quotation.status, toolLossRate: quotation.toolLossRate.toString(), generalAdminRate: quotation.generalAdminRate.toString(), safetyHealthRate: quotation.safetyHealthRate.toString(), items: quotation.items.map((item) => ({ productId: item.productId, costCategory: item.costCategory, name: item.name, specification: item.specification ?? "", unit: item.unit, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), discountRate: item.discountRate.toString(), note: item.note ?? "" })) };
  return <div className="p-8"><div className="flex items-start justify-between"><PageHeader title="견적서 상세·수정" description={`${quotation.quotationNumber} / Rev.${quotation.revision}`} /><QuotationStatusBadge status={quotation.status} /></div><Notice success={query.success} error={query.error ?? (!quotation.supplierProfileId ? "공급자 정보가 지정되지 않았습니다." : needsRecalculation ? "공사용 견적 계산 방식으로 다시 계산이 필요합니다." : undefined)} /><div className="mt-4 flex justify-end gap-3"><button className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white" form="quotation-form" type="submit">수정 저장</button><Link className="rounded-lg border px-5 py-2.5 text-sm font-semibold text-blue-700" href={`/quotations/${id}/print`}>견적서 미리보기</Link><Link className="rounded-lg border px-5 py-2.5 text-sm font-semibold text-blue-700" href={`/quotations/${id}/print`}>PDF/인쇄</Link><a className="rounded-lg border px-5 py-2.5 text-sm font-semibold text-blue-700" href={`/api/quotations/${id}/excel`}>Excel 다운로드</a><Link className="rounded-lg border px-5 py-2.5 text-sm font-semibold text-blue-700" href={`/orders/new?quotationId=${id}`}>오더 생성</Link><Link className="rounded-lg border px-5 py-2.5 text-sm font-semibold text-blue-700" href={`/procurement/rfqs/new?quotationId=${id}`}>구매 견적요청 생성</Link><form action={createStatementFromQuotation}><input type="hidden" name="id" value={id}/><label className="mr-2 text-xs"><input type="checkbox" name="includeAutomaticItems"/> 자동 계산 항목 포함</label><SubmitButton>거래명세서 생성</SubmitButton></form><form action={createQuotationRevision}><input type="hidden" name="id" value={id} /><SubmitButton>개정본 만들기</SubmitButton></form><form action={deleteQuotation}><input type="hidden" name="id" value={id} /><SubmitButton danger>견적서 삭제</SubmitButton></form></div><QuotationForm suppliers={suppliers} clients={clients} products={products.map((product) => ({ id: product.id, name: product.name, specification: product.specification, unit: product.unit, defaultPrice: product.defaultPrice.toString() }))} initial={initial} /></div>;
}
