import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { calculateReceivedAmount } from "@/features/procurement/calculations";
import { buildPurchaseHistoryWorkbook } from "@/features/procurement/purchase-history-excel";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
export async function GET(request: Request) {
  const session = await auth();
  if (!session?.user || !["ADMIN", "MANAGER", "ACCOUNTING"].includes(session.user.role)) return NextResponse.json({ error: "권한이 없습니다." }, { status: 403 });
  const query = new URL(request.url).searchParams;
  const now = new Date(), start = query.get("startDate") ? new Date(`${query.get("startDate")}T00:00:00Z`) : new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)), end = query.get("endDate") ? new Date(`${query.get("endDate")}T00:00:00Z`) : new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)); end.setUTCDate(end.getUTCDate() + (query.get("endDate") ? 1 : 0));
  const rows = await db.purchaseOrder.findMany({ where: { deletedAt: null, orderDate: { gte: start, lt: end }, supplierId: query.get("supplierId") || undefined }, include: { supplier: true, project: true, sourceQuotation: true, sourceOrder: true, items: { include: { receiptItems: { where: { goodsReceipt: { deletedAt: null, status: { not: "CANCELED" } } } } } }, disbursements: { where: { deletedAt: null } } }, orderBy: { orderDate: "asc" } });
  const orders = rows.map((order) => ({ purchaseOrderNumber: order.purchaseOrderNumber, orderDate: order.orderDate, supplierCode: order.supplier.clientCode, supplierName: order.supplier.companyName, businessNumber: order.supplier.businessNumber, projectCode: order.project?.projectCode ?? "", projectName: order.project?.projectName ?? "", quotationNumber: order.sourceQuotation ? `${order.sourceQuotation.quotationNumber} Rev.${order.sourceQuotation.revision}` : "", orderNumber: order.sourceOrder?.orderNumber ?? "", subtotal: Number(order.subtotal), vatAmount: Number(order.vatAmount), totalAmount: Number(order.totalAmount), receivedAmount: calculateReceivedAmount(order.items.map((item) => ({ orderedQuantity: Number(item.orderedQuantity), unitPrice: Number(item.unitPrice), receivedQuantity: item.receiptItems.reduce((sum, receipt) => sum + Number(receipt.receivedQuantity), 0) }))), paidAmount: order.disbursements.filter((payment) => payment.status === "EXECUTED").reduce((sum, payment) => sum + Number(payment.totalAmount), 0), status: order.status, items: order.items.map((item) => ({ maker: item.maker ?? "", modelName: item.modelName ?? item.itemCode ?? "", name: item.name, quantity: Number(item.orderedQuantity), unitPrice: Number(item.unitPrice), totalAmount: Number(item.totalAmount) })), payments: order.disbursements.map((payment) => ({ number: payment.disbursementNumber, type: payment.paymentType, status: payment.status, plannedDate: payment.plannedDate, executedDate: payment.executedDate, totalAmount: Number(payment.totalAmount) })) }));
  const workbook = await buildPurchaseHistoryWorkbook(orders, `${start.toISOString().slice(0, 10)} ~ ${new Date(end.getTime() - 86_400_000).toISOString().slice(0, 10)}`), buffer = await workbook.xlsx.writeBuffer(), fileName = `공급업체별_구매내역_${start.toISOString().slice(0, 10).replaceAll("-", "")}_${new Date(end.getTime() - 86_400_000).toISOString().slice(0, 10).replaceAll("-", "")}.xlsx`;
  return new NextResponse(new Uint8Array(buffer), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(fileName)}`, "Cache-Control": "private, no-store" } });
}
