import type { QuotationStatus } from "@prisma/client";
import Link from "next/link";
import { card, Empty, input, Notice, PageHeader } from "@/components/common/page";
import { QuotationStatusBadge } from "@/components/common/quotation-status-badge";
import { db } from "@/lib/db";
export const dynamic = "force-dynamic";
const statuses = [["", "전체 상태"], ["DRAFT", "작성 중"], ["REVIEW_REQUESTED", "검토 요청"], ["APPROVED", "승인"], ["REJECTED", "반려"], ["SENT", "발송"], ["NEGOTIATING", "협의 중"], ["CONTRACTED", "계약"], ["ON_HOLD", "보류"], ["CANCELED", "취소"], ["EXPIRED", "만료"]];
const allowedStatuses = new Set(statuses.map(([value]) => value).filter(Boolean));
const won = (value: { toString(): string }) => `${Number(value).toLocaleString("ko-KR")}원`;
const date = (value: Date | null) => value ? value.toISOString().slice(0, 10) : "-";
export default async function QuotationsPage({ searchParams }: { searchParams: Promise<{ search?: string; status?: string; clientId?: string; startDate?: string; endDate?: string; success?: string; error?: string }> }) {
  const query = await searchParams, search = query.search?.trim() ?? "", status = allowedStatuses.has(query.status ?? "") ? query.status as QuotationStatus : undefined; const clients = await db.client.findMany({ where: { deletedAt: null }, select: { id: true, companyName: true }, orderBy: { companyName: "asc" } }); const startDate = query.startDate ? new Date(`${query.startDate}T00:00:00.000Z`) : undefined, endDate = query.endDate ? new Date(`${query.endDate}T23:59:59.999Z`) : undefined;
  const quotations = await db.quotation.findMany({ where: { deletedAt: null, ...(status ? { status } : {}), ...(query.clientId ? { clientId: query.clientId } : {}), ...(startDate || endDate ? { quotationDate: { gte: startDate, lte: endDate } } : {}), ...(search ? { OR: [{ quotationNumber: { contains: search } }, { projectName: { contains: search } }, { title: { contains: search } }, { client: { companyName: { contains: search } } }] } : {}) }, include: { client: true }, orderBy: { updatedAt: "desc" } });
  return <div className="p-8"><PageHeader title="견적서 관리" description="거래처별 견적서와 개정본을 관리합니다." href="/quotations/new" actionLabel="견적서 등록" /><Notice success={query.success} error={query.error} /><form className={`${card} mt-6 grid grid-cols-6 gap-3 p-4`}><input className={`${input} col-span-2 mt-0`} name="search" defaultValue={search} placeholder="견적번호, 거래처, 프로젝트명, 제목" /><select className={`${input} mt-0`} name="status" defaultValue={query.status ?? ""}>{statuses.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select><select className={`${input} mt-0`} name="clientId" defaultValue={query.clientId ?? ""}><option value="">전체 거래처</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.companyName}</option>)}</select><input className={`${input} mt-0`} type="date" name="startDate" defaultValue={query.startDate ?? ""} title="견적일 시작" /><input className={`${input} mt-0`} type="date" name="endDate" defaultValue={query.endDate ?? ""} title="견적일 종료" /><div className="col-span-6 flex justify-end"><button className="rounded-lg border px-5 py-2 text-sm">검색·필터 적용</button></div></form><div className={`${card} mt-4 overflow-x-auto`}>{quotations.length === 0 ? <Empty message="조건에 맞는 견적서가 없습니다." /> : <table className="min-w-[1550px] w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{["견적번호", "개정", "거래처", "프로젝트명", "견적 제목", "견적일", "유효기간", "납품기한", "상태", "공급가액", "부가세", "합계금액", "수정일", "출력"].map((title) => <th className="p-3" key={title}>{title}</th>)}</tr></thead><tbody>{quotations.map((quotation) => <tr className="border-t hover:bg-slate-50" key={quotation.id}><td className="p-3 font-semibold"><Link className="text-blue-600" href={`/quotations/${quotation.id}`}>{quotation.quotationNumber}</Link></td><td>Rev.{quotation.revision}</td><td>{quotation.client.companyName}</td><td>{quotation.projectName}</td><td><Link className="font-medium text-blue-600" href={`/quotations/${quotation.id}`}>{quotation.title}</Link></td><td>{date(quotation.quotationDate)}</td><td>{date(quotation.validUntil)}</td><td>{quotation.deliveryDeadlineType === "DATE" ? date(quotation.deliveryDeadlineDate) : "협의 필요"}</td><td><QuotationStatusBadge status={quotation.status} /></td><td className="text-right">{won(quotation.subtotal)}</td><td className="text-right">{won(quotation.vatAmount)}</td><td className="text-right font-semibold">{won(quotation.totalAmount)}</td><td>{date(quotation.updatedAt)}</td><td><div className="flex gap-2"><Link className="text-blue-600" href={`/quotations/${quotation.id}/print`}>미리보기</Link><Link className="text-blue-600" href={`/quotations/${quotation.id}/print`}>PDF/인쇄</Link><a className="text-blue-600" href={`/api/quotations/${quotation.id}/excel`}>Excel</a></div></td></tr>)}</tbody></table>}</div></div>;
}
