import type { EvidenceType, ExpenseStatus, PaymentMethod } from "@prisma/client";
export type ProjectCostPasteContext={categories:Array<{id:string;name:string}>;suppliers:Array<{id:string;companyName:string}>};
export type ParsedProjectCostRow={sourceRow:number;expenseDate:string;expenseCategoryId:string;expenseCategoryName:string;supplierId:string|null;supplierName:string;description:string;quantity:string;unitPrice:string;vatRate:0|10;paymentMethod:PaymentMethod;evidenceType:EvidenceType;status:ExpenseStatus;payerName:string;memo:string;errors:string[]};
const payment:Record<string,PaymentMethod>={현금:"CASH",개인카드:"CARD",카드:"CARD",계좌이체:"BANK_TRANSFER",법인카드:"CORPORATE_CARD",기타:"OTHER"};
const evidence:Record<string,EvidenceType>={세금계산서:"TAX_INVOICE",카드영수증:"CARD_RECEIPT",현금영수증:"CASH_RECEIPT",간이영수증:"SIMPLE_RECEIPT","증빙 없음":"NONE",없음:"NONE"};
const status:Record<string,ExpenseStatus>={예정:"DRAFT","승인 요청":"APPROVAL_REQUESTED",확정:"APPROVED",반려:"REJECTED","지급 완료":"PAID",취소:"CANCELED"};
function validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return !Number.isNaN(date.valueOf())&&date.toISOString().slice(0,10)===value}
function header(columns:string[]){return columns.slice(0,5).filter(value=>["비용일자","비용구분","지급처","비용명","수량"].includes(value.replace(/\s/g,""))).length>=3}
export function parseProjectCostPaste(text:string,context:ProjectCostPasteContext):ParsedProjectCostRow[]{const lines=text.replace(/\r/g,"").split("\n").map((line,index)=>({line,sourceRow:index+1})).filter(({line})=>line.trim());return lines.filter(({line},index)=>!(index===0&&header(line.split("\t").map(v=>v.trim())))).map(({line,sourceRow})=>{const [expenseDate="",categoryName="",supplierName="",description="",rawQuantity="",rawPrice="",rawVat="",rawPayment="",rawEvidence="",rawStatus="",payerName="",memo=""]=line.split("\t").map(v=>v.trim()),quantity=rawQuantity||"1",unitPrice=rawPrice.replace(/,/g,""),normalizedVat=rawVat.replace(/\s/g,""),vatRate:0|10=["10%","10","과세"].includes(normalizedVat)?10:0,category=context.categories.find(item=>item.name===categoryName),supplier=context.suppliers.find(item=>item.companyName===supplierName),errors:string[]=[];if(!validDate(expenseDate))errors.push("비용일자는 YYYY-MM-DD 형식의 유효한 날짜여야 합니다.");if(!category)errors.push("존재하지 않는 비용구분입니다.");if(!description)errors.push("비용명은 필수입니다.");if(!/^\d+(?:\.\d{1,4})?$/.test(quantity)||Number(quantity)<=0)errors.push("수량은 0보다 큰 숫자여야 합니다.");if(!/^\d+$/.test(unitPrice)||!Number.isSafeInteger(Number(unitPrice)))errors.push("단가는 원 단위 숫자여야 합니다.");if(!["10%","10","과세","없음","0","면세"].includes(normalizedVat))errors.push("부가세는 10% 또는 없음으로 입력해 주세요.");if(!payment[rawPayment])errors.push("지급방법을 확인해 주세요.");if(!evidence[rawEvidence])errors.push("증빙종류를 확인해 주세요.");if(!status[rawStatus])errors.push("상태를 확인해 주세요.");return{sourceRow,expenseDate,expenseCategoryId:category?.id??"",expenseCategoryName:categoryName,supplierId:supplier?.id??null,supplierName:supplierName||"",description,quantity,unitPrice,vatRate,paymentMethod:payment[rawPayment]??"OTHER",evidenceType:evidence[rawEvidence]??"NONE",status:status[rawStatus]??"DRAFT",payerName,memo,errors}})}
