import type{CashflowClientRow,CashflowPeriodRow,CashflowSummary,CashflowTransaction}from"@/features/reports/types";
export type GroupUnit="day"|"week"|"month"|"quarter"|"year";
export const toWon=(value:{toString():string}|string|number|bigint):bigint=>typeof value==="bigint"?value:BigInt(Math.round(Number(value)));
export function seoulDateBounds(start:string,end:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))throw new Error("날짜 형식이 올바르지 않습니다.");const from=new Date(`${start}T00:00:00+09:00`),until=new Date(`${end}T00:00:00+09:00`);until.setUTCDate(until.getUTCDate()+1);if(from>=until)throw new Error("종료일은 시작일보다 빠를 수 없습니다.");return{from,until};}
export const seoulDateKey=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
export function mergeCashflowTransactions(inflows:CashflowTransaction[],outflows:CashflowTransaction[]){return[...inflows,...outflows].sort((a,b)=>b.transactionDate.getTime()-a.transactionDate.getTime()||a.documentNumber.localeCompare(b.documentNumber));}
export function summarizeCashflow(rows:CashflowTransaction[]):CashflowSummary{let inflow=0n,outflow=0n,inflowCount=0,outflowCount=0;for(const r of rows)if(r.type==="INFLOW"){inflow+=r.amount;inflowCount++}else{outflow+=r.amount;outflowCount++}return{inflowCount,outflowCount,inflow,outflow,net:inflow-outflow,totalCount:rows.length}}
function mondayKey(date:Date){const key=seoulDateKey(date),local=new Date(`${key}T00:00:00+09:00`),day=(local.getUTCDay()+6)%7;local.setUTCDate(local.getUTCDate()-day);return seoulDateKey(local)}
function periodKey(date:Date,unit:GroupUnit){const day=seoulDateKey(date),[y,m]=day.split("-").map(Number);if(unit==="day")return day;if(unit==="week")return mondayKey(date);if(unit==="month")return `${y}-${String(m).padStart(2,"0")}`;if(unit==="quarter")return `${y} Q${Math.ceil(m/3)}`;return String(y)}
export function groupCashflowByPeriod(rows:CashflowTransaction[],unit:GroupUnit):CashflowPeriodRow[]{const groups=new Map<string,CashflowTransaction[]>();for(const r of rows){const key=periodKey(r.transactionDate,unit);groups.set(key,[...(groups.get(key)??[]),r])}let cumulativeNet=0n;return[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([key,list])=>{const s=summarizeCashflow(list);cumulativeNet+=s.net;return{key,label:unit==="week"?`${key} 주`:key,...s,cumulativeNet}})}
export const groupCashflowByDay=(r:CashflowTransaction[])=>groupCashflowByPeriod(r,"day");export const groupCashflowByWeek=(r:CashflowTransaction[])=>groupCashflowByPeriod(r,"week");export const groupCashflowByMonth=(r:CashflowTransaction[])=>groupCashflowByPeriod(r,"month");export const groupCashflowByQuarter=(r:CashflowTransaction[])=>groupCashflowByPeriod(r,"quarter");export const groupCashflowByYear=(r:CashflowTransaction[])=>groupCashflowByPeriod(r,"year");
export function calculateCumulativeNetCashflow(rows:Array<{inflow:bigint;outflow:bigint}>){let total=0n;return rows.map(r=>total+=r.inflow-r.outflow)}
export function groupCashflowByClient(rows:CashflowTransaction[]):CashflowClientRow[]{const groups=new Map<string,CashflowTransaction[]>();for(const r of rows){const key=r.clientId??`name:${r.clientName}`;groups.set(key,[...(groups.get(key)??[]),r])}return[...groups].map(([key,list])=>{const first=list[0],summary=summarizeCashflow(list),inDates=list.filter(x=>x.type==="INFLOW").map(x=>x.transactionDate),outDates=list.filter(x=>x.type==="OUTFLOW").map(x=>x.transactionDate);return{key,clientId:first.clientId,clientCode:first.clientCode,clientName:first.clientName,clientType:first.clientType,businessNumber:first.businessNumber,...summary,latestInflow:inDates.length?new Date(Math.max(...inDates.map(x=>x.getTime()))):null,latestOutflow:outDates.length?new Date(Math.max(...outDates.map(x=>x.getTime()))):null,projectCount:new Set(list.map(x=>x.projectId).filter(Boolean)).size}})}
export function groupCashflowByProject(rows:CashflowTransaction[]){const groups=new Map<string,CashflowTransaction[]>();for(const r of rows){const key=r.projectId??"none";groups.set(key,[...(groups.get(key)??[]),r])}return[...groups].map(([key,list])=>({key,projectId:list[0].projectId,projectCode:list[0].projectCode,projectName:list[0].projectName??"프로젝트 미지정",...summarizeCashflow(list)}))}
export function calculatePeriodComparison(current:CashflowSummary,previous:CashflowSummary){const rate=(now:bigint,before:bigint)=>before===0n?null:Number((now-before)*10000n/before)/100;return{inflowChange:current.inflow-previous.inflow,inflowRate:rate(current.inflow,previous.inflow),outflowChange:current.outflow-previous.outflow,outflowRate:rate(current.outflow,previous.outflow),netChange:current.net-previous.net}}
export function previousPeriod(from:Date,until:Date){const duration=until.getTime()-from.getTime();return{from:new Date(from.getTime()-duration),until:new Date(from)}}
