import { Prisma } from "@prisma/client";
import { calculateConstructionQuotationTotals, calculateQuotationItemAmount, type QuotationCostCategory } from "@/lib/construction-quotation";
export type QuotationCalculationInput = { productId?: string | null; costCategory?: QuotationCostCategory; name: string; specification?: string | null; unit: string; quantity: string; unitPrice: string; discountRate: string; note?: string | null };
function money(value: bigint) { if (value > BigInt(Number.MAX_SAFE_INTEGER)) throw new RangeError("금액이 허용 범위를 초과했습니다."); return Number(value); }
export function calculateQuotationPersistence(items: QuotationCalculationInput[], rates: { toolLossRate: string; generalAdminRate: string; safetyHealthRate: string } = { toolLossRate: "0", generalAdminRate: "0", safetyHealthRate: "0" }) {
  let subtotal = 0n, discountAmount = 0n;
  const normalized = items.map(item => ({ ...item, costCategory: item.costCategory ?? "MATERIAL" as const }));
  const calculated = normalized.map((item, index) => { const result = calculateQuotationItemAmount(item); subtotal += result.baseAmount; discountAmount += result.discountAmount; const vatAmount = (result.supplyAmount * 10n + 50n) / 100n; return { productId: item.productId || null, costCategory: item.costCategory, sortOrder: index + 1, name: item.name, specification: item.specification || null, unit: item.unit, quantity: new Prisma.Decimal(item.quantity), unitPrice: money(BigInt(item.unitPrice)), discountRate: new Prisma.Decimal(item.discountRate), supplyAmount: money(result.supplyAmount), vatAmount: money(vatAmount), totalAmount: money(result.supplyAmount + vatAmount), taxType: "TAXABLE" as const, note: item.note || null }; });
  const totals = calculateConstructionQuotationTotals(normalized, rates);
  return { calculated, totals: { subtotal: money(subtotal), discountAmount: money(discountAmount), materialAmount: money(totals.materialAmount), laborAmount: money(totals.laborAmount), expenseAmount: money(totals.expenseAmount), travelAmount: money(totals.travelAmount), directCostAmount: money(totals.directCostAmount), toolLossRate: new Prisma.Decimal(rates.toolLossRate), toolLossAmount: money(totals.toolLossAmount), generalAdminRate: new Prisma.Decimal(rates.generalAdminRate), generalAdminAmount: money(totals.generalAdminAmount), safetyHealthRate: new Prisma.Decimal(rates.safetyHealthRate), safetyHealthAmount: money(totals.safetyHealthAmount), taxableAmount: money(totals.taxableAmount), vatAmount: money(totals.vatAmount), totalAmount: money(totals.totalAmount) } };
}
