"use client";
import { useState } from "react";
import type { Client, ExpenseCategory } from "@prisma/client";
import { input } from "@/components/common/page";
import { savePastedExpenses } from "@/features/project-costs/actions";
import { calculateExpenseAmounts } from "@/features/project-costs/calculations";
import { parseProjectCostPaste, type ParsedProjectCostRow } from "@/lib/project-cost-paste";
import { SubmitButton } from "./submit-button";
export function ProjectCostPasteDialog({projectId,categories,suppliers}:{projectId:string;categories:ExpenseCategory[];suppliers:Client[]}){const [open,setOpen]=useState(false),[text,setText]=useState(""),[rows,setRows]=useState<ParsedProjectCostRow[]>([]);const check=()=>setRows(parseProjectCostPaste(text,{categories,suppliers}));const valid=rows.length>0&&rows.every(r=>!r.errors.length);const payload=rows.map(r=>({expenseDate:r.expenseDate,expenseCategoryId:r.expenseCategoryId,supplierId:r.supplierId,supplierName:r.supplierName,description:r.description,quantity:r.quantity,unitPrice:r.unitPrice,vatRate:r.vatRate,paymentMethod:r.paymentMethod,evidenceType:r.evidenceType,status:r.status,payerName:r.payerName,memo:r.memo,amountInputType:"SUPPLY"}));return <div><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>setOpen(v=>!v)} type="button">엑셀 붙여넣기</button>{open&&<div className="mt-4 rounded-xl border bg-white p-5"><p className="mb-2 text-sm text-slate-600">비용일자 | 비용구분 | 지급처 | 비용명 | 수량 | 단가 | 부가세 | 지급방법 | 증빙 | 상태 | 지급자 | 메모 순서로 붙여 넣으세요.</p><textarea className={input} onChange={e=>setText(e.target.value)} rows={6} value={text}/><div className="mt-3 flex gap-2"><button className="rounded-lg border px-4 py-2 text-sm" onClick={check} type="button">데이터 확인</button><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>{setOpen(false);setRows([])}} type="button">취소</button></div>{rows.length>0&&<><div className="mt-4 overflow-x-auto"><table className="w-full text-xs"><thead><tr className="bg-slate-50"><th>행</th><th>일자</th><th>구분</th><th>지급처</th><th>비용명</th><th>공급가</th><th>VAT</th><th>합계</th><th>오류</th></tr></thead><tbody>{rows.map(r=>{let a={supplyAmount:0,vatAmount:0,totalAmount:0};try{a=calculateExpenseAmounts({quantity:r.quantity,unitPrice:Number(r.unitPrice),vatRate:r.vatRate,amountInputType:"SUPPLY"})}catch{}return <tr className="border-b" key={r.sourceRow}><td>{r.sourceRow}</td><td>{r.expenseDate}</td><td>{r.expenseCategoryName}</td><td>{r.supplierName}</td><td>{r.description}</td><td className="text-right">{a.supplyAmount.toLocaleString()}</td><td className="text-right">{a.vatAmount.toLocaleString()}</td><td className="text-right">{a.totalAmount.toLocaleString()}</td><td className="text-red-600">{r.errors.join(" ")}</td></tr>})}</tbody></table></div><form action={savePastedExpenses} className="mt-4 flex justify-end"><input name="projectId" type="hidden" value={projectId}/><input name="rows" type="hidden" value={JSON.stringify(payload)}/><SubmitButton disabled={!valid} label="비용 등록"/></form></>}</div>}</div>}
