"use client";
import { calculateQuotationItemAmount, quotationCostCategoryLabels, type QuotationCostCategory } from "@/lib/construction-quotation";
import { QuotationPasteDialog } from "./quotation-paste-dialog";
export type QuotationEditorItem = { productId: string | null; costCategory: QuotationCostCategory; name: string; specification: string; unit: string; quantity: string; unitPrice: string; discountRate: string; note: string };
export type ProductOption = { id: string; name: string; specification: string | null; unit: string; defaultPrice: string };
export const blankQuotationItem = (): QuotationEditorItem => ({ productId: null, costCategory: "MATERIAL", name: "", specification: "", unit: "개", quantity: "1", unitPrice: "0", discountRate: "0", note: "" });
const amount = (item: QuotationEditorItem) => { try { return calculateQuotationItemAmount(item).supplyAmount; } catch { return 0n; } };
const won = (value: bigint) => `${value.toLocaleString("ko-KR")}원`;
export function QuotationItemsEditor({ items, products, onChange }: { items: QuotationEditorItem[]; products: ProductOption[]; onChange: (items: QuotationEditorItem[]) => void }) {
  const patch = (index: number, value: Partial<QuotationEditorItem>) => onChange(items.map((item, i) => i === index ? { ...item, ...value } : item));
  const move = (index: number, offset: number) => { const target=index+offset;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];onChange(next); };
  const selectProduct=(index:number,id:string)=>{const product=products.find(x=>x.id===id);patch(index,product?{productId:id,name:product.name,specification:product.specification??"",unit:product.unit,unitPrice:product.defaultPrice}:{productId:null});};
  return <div className="overflow-x-auto rounded-xl border bg-white"><div className="flex items-center justify-between p-5"><div><h3 className="font-bold">공사 견적 품목</h3><p className="mt-1 text-xs text-slate-500">공구손료·일반관리비·산업안전보건관리비는 아래 비율로 자동 계산됩니다.</p></div><div className="flex gap-2"><QuotationPasteDialog currentItems={items} onApply={onChange}/><button type="button" onClick={()=>onChange([...items,blankQuotationItem()])} className="rounded-lg border px-3 py-2 text-sm">품목 추가</button></div></div><table className="min-w-[1450px] w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{["번호","비용구분","기본 품목","품명","규격","단위","수량","단가","할인율","공급가액","비고","이동/삭제"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{items.map((item,index)=><tr className="border-t align-top" key={index}><td className="p-3 text-center">{index+1}</td><td className="p-2"><select className="w-28 rounded border p-2" value={item.costCategory} onChange={e=>patch(index,{costCategory:e.target.value as QuotationCostCategory})}>{Object.entries(quotationCostCategoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="p-2"><select className="w-32 rounded border p-2" value={item.productId??""} onChange={e=>selectProduct(index,e.target.value)}><option value="">직접 입력</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td>{(["name","specification","unit","quantity","unitPrice","discountRate"] as const).map(key=><td className="p-2" key={key}><input required={key==="name"||key==="unit"||key==="quantity"} type={["quantity","unitPrice","discountRate"].includes(key)?"number":"text"} min="0" max={key==="discountRate"?100:undefined} step={key==="quantity"?"0.0001":key==="discountRate"?"0.01":"1"} className="w-28 rounded border p-2" value={item[key]} onChange={e=>patch(index,{[key]:e.target.value})}/></td>)}<td className="p-3 text-right font-semibold">{won(amount(item))}</td><td className="p-2"><input className="w-36 rounded border p-2" value={item.note} onChange={e=>patch(index,{note:e.target.value})}/></td><td className="p-2 whitespace-nowrap"><button type="button" onClick={()=>move(index,-1)} disabled={!index}>↑</button> <button type="button" onClick={()=>move(index,1)} disabled={index===items.length-1}>↓</button> <button type="button" className="text-red-600" disabled={items.length===1} onClick={()=>onChange(items.filter((_,i)=>i!==index))}>삭제</button></td></tr>)}</tbody></table></div>;
}
