"use client";
import { useState } from "react";
import { calculateQuotationItemValues } from "@/lib/calculations";
import { mergeQuotationPasteItems, parseQuotationPaste, type PasteMode, type ParsedPasteRow } from "@/lib/quotation-paste";
import type { QuotationEditorItem } from "./quotation-items-editor";
const won = (value: bigint) => `${Number(value).toLocaleString("ko-KR")}원`;
function amount(row: ParsedPasteRow) { try { return calculateQuotationItemValues(row.quantity, Number(row.unitPrice), Number(row.discountRate), "TAXABLE"); } catch { return { supplyAmount: 0n, vatAmount: 0n, totalAmount: 0n }; } }
export function QuotationPasteDialog({ currentItems, onApply }: { currentItems: QuotationEditorItem[]; onApply: (items: QuotationEditorItem[]) => void }) {
  const [open, setOpen] = useState(false), [text, setText] = useState(""), [rows, setRows] = useState<ParsedPasteRow[]>([]), [mode, setMode] = useState<PasteMode>("append"), hasErrors = rows.some((row) => row.errors.length > 0);
  const close = () => { setOpen(false); setText(""); setRows([]); };
  const apply = () => { if (!rows.length || hasErrors) return; const items: QuotationEditorItem[] = rows.map((row) => ({ productId: null, name: row.name, specification: row.specification, unit: row.unit, quantity: row.quantity, unitPrice: row.unitPrice, discountRate: row.discountRate, note: row.note })); onApply(mergeQuotationPasteItems(currentItems, items, mode)); close(); };
  return <div><button type="button" onClick={() => setOpen((value) => !value)} className="rounded-lg border border-blue-300 bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700">엑셀 데이터 붙여넣기</button>{open && <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50/40 p-5"><p className="text-sm font-semibold">Excel 열 순서: 품명 | 규격 | 단위 | 수량 | 단가 | 할인율 | 비고</p><textarea className="mt-3 h-36 w-full rounded-lg border bg-white p-3 font-mono text-sm" value={text} onChange={(event) => { setText(event.target.value); setRows([]); }} placeholder="Excel에서 행을 복사한 후 여기에 붙여넣으세요." /><div className="mt-3 flex items-center gap-3"><button type="button" onClick={() => setRows(parseQuotationPaste(text))} className="rounded-lg border bg-white px-4 py-2 text-sm">데이터 확인</button><select className="rounded-lg border bg-white px-3 py-2 text-sm" value={mode} onChange={(event) => setMode(event.target.value as PasteMode)}><option value="append">기존 품목 뒤에 추가</option><option value="replace">기존 품목 전체 교체</option></select><button type="button" disabled={!rows.length || hasErrors} onClick={apply} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">품목에 적용</button><button type="button" onClick={close} className="rounded-lg border bg-white px-4 py-2 text-sm">취소</button></div>{rows.length > 0 && <div className="mt-4 overflow-x-auto rounded-lg border bg-white"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50"><tr>{["번호", "품명", "규격", "단위", "수량", "단가", "할인율", "공급가액", "부가세", "합계금액", "오류"].map((title) => <th className="p-2 text-left" key={title}>{title}</th>)}</tr></thead><tbody>{rows.map((row) => { const value = amount(row); return <tr className="border-t" key={row.sourceRow}><td className="p-2">{row.sourceRow}</td><td>{row.name}</td><td>{row.specification || "-"}</td><td>{row.unit}</td><td>{row.quantity}</td><td className="text-right">{Number(row.unitPrice || 0).toLocaleString()}</td><td className="text-right">{row.discountRate}%</td><td className="text-right">{won(value.supplyAmount)}</td><td className="text-right">{won(value.vatAmount)}</td><td className="text-right">{won(value.totalAmount)}</td><td className="max-w-xs p-2 text-red-600">{row.errors.join(" ") || "-"}</td></tr>; })}</tbody></table></div>}</div>}</div>;
}
