"use client";
import Link from "next/link";
import { useState } from "react";
import { input, label } from "@/components/common/page";
import { saveQuotation } from "@/features/quotations/actions";
import { QuotationItemsEditor, blankQuotationItem, type ProductOption, type QuotationEditorItem } from "./quotation-items-editor";
import { SubmitButton } from "./submit-button";
export type QuotationFormValue = { id: string; clientId: string; projectName: string; title: string; quotationDate: string; validUntil: string; expectedStartDate: string; expectedEndDate: string; paymentTerms: string; deliveryTerms: string; note: string; status: string; items: QuotationEditorItem[] };
const statuses = [["DRAFT", "작성 중"], ["REVIEW_REQUESTED", "검토 요청"], ["APPROVED", "승인"], ["REJECTED", "반려"], ["SENT", "발송"], ["NEGOTIATING", "협의 중"], ["CONTRACTED", "계약"], ["ON_HOLD", "보류"], ["CANCELED", "취소"], ["EXPIRED", "만료"]];
export function QuotationForm({ clients, products, initial }: { clients: { id: string; companyName: string }[]; products: ProductOption[]; initial?: QuotationFormValue }) {
  const [items, setItems] = useState<QuotationEditorItem[]>(initial?.items.length ? initial.items : [blankQuotationItem()]);
  return <form action={saveQuotation} className="mt-6 space-y-5"><input type="hidden" name="id" value={initial?.id ?? ""} /><input type="hidden" name="items" value={JSON.stringify(items)} /><div className="rounded-xl border bg-white p-6"><div className="grid grid-cols-3 gap-5"><label className={label}>거래처 *<select required className={input} name="clientId" defaultValue={initial?.clientId ?? ""}><option value="">거래처 선택</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.companyName}</option>)}</select></label><label className={label}>프로젝트명 *<input required className={input} name="projectName" defaultValue={initial?.projectName ?? ""} /></label><label className={label}>견적 제목 *<input required className={input} name="title" defaultValue={initial?.title ?? ""} /></label><label className={label}>견적일 *<input required type="date" className={input} name="quotationDate" defaultValue={initial?.quotationDate ?? new Date().toISOString().slice(0, 10)} /></label><label className={label}>유효기간<input type="date" className={input} name="validUntil" defaultValue={initial?.validUntil ?? ""} /></label><label className={label}>상태<select className={input} name="status" defaultValue={initial?.status ?? "DRAFT"}>{statuses.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className={label}>예상 시작일<input type="date" className={input} name="expectedStartDate" defaultValue={initial?.expectedStartDate ?? ""} /></label><label className={label}>예상 종료일<input type="date" className={input} name="expectedEndDate" defaultValue={initial?.expectedEndDate ?? ""} /></label><label className={label}>결제조건<input className={input} name="paymentTerms" defaultValue={initial?.paymentTerms ?? ""} /></label><label className={label}>납품조건<input className={input} name="deliveryTerms" defaultValue={initial?.deliveryTerms ?? ""} /></label></div><label className={`${label} mt-5 block`}>비고<textarea className={input} rows={3} name="note" defaultValue={initial?.note ?? ""} /></label></div><QuotationItemsEditor items={items} products={products} onChange={setItems} /><div className="flex justify-end gap-3"><Link className="rounded-lg border px-5 py-2.5 text-sm" href="/quotations">취소</Link><SubmitButton /></div></form>;
}
