"use server";
import type { Route } from "next";
import { Prisma, QuotationStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { nextDocumentNumber } from "@/lib/document-number";

const required=z.string().trim().min(1,"필수 입력 항목입니다.");
const optional=z.string().trim().transform(v=>v||null);
const money=z.coerce.number().int("금액은 원 단위 정수로 입력해 주세요.").min(0).max(Number.MAX_SAFE_INTEGER);
const decimal=z.coerce.number().positive();
const date=z.coerce.date();
const clientSchema=z.object({companyName:required,businessNumber:required,representativeName:optional,contactName:optional,contactPhone:optional,contactEmail:z.union([z.literal(""),z.string().email("이메일 형식을 확인해 주세요.")]).transform(v=>v||null),address:optional,paymentTerms:optional,memo:optional});
const productSchema=z.object({productCode:required,name:required,specification:optional,unit:required,defaultPrice:money,taxType:z.enum(["TAXABLE","ZERO_RATED","TAX_EXEMPT"]),category:optional});
const projectSchema=z.object({clientId:required,projectName:required,managerId:required,startDate:date,expectedEndDate:z.union([z.literal(""),date]).transform(v=>v||null),contractAmount:money,budgetAmount:money,status:z.enum(["PLANNED","QUOTING","CONTRACTED","IN_PROGRESS","PAUSED","COMPLETED","SETTLING","CLOSED","CANCELED"]),description:optional});
const expenseSchema=z.object({projectId:required,expenseCategoryId:required,supplierId:optional,expenseDate:date,description:required,quantity:decimal,unitPrice:money,taxable:z.enum(["yes","no"]),paymentMethod:z.enum(["CASH","CARD","BANK_TRANSFER","CORPORATE_CARD","OTHER"]),evidenceType:z.enum(["TAX_INVOICE","CARD_RECEIPT","CASH_RECEIPT","SIMPLE_RECEIPT","NONE"]),evidenceNumber:optional,memo:optional});
const paymentSchema=z.object({projectId:required,paymentDate:date,amount:money,paymentType:z.enum(["ADVANCE","INTERIM","BALANCE","FULL","OTHER"]),paymentMethod:optional,memo:optional});
const itemSchema=z.object({productId:z.string().nullable().optional(),name:required,specification:z.string().nullable().optional(),unit:required,quantity:z.number().positive(),unitPrice:z.number().int().min(0),discountRate:z.number().min(0).max(100),taxType:z.enum(["TAXABLE","ZERO_RATED","TAX_EXEMPT"])});
const quotationSchema=z.object({clientId:required,projectName:required,title:required,quotationDate:date,validUntil:z.union([z.literal(""),date]).transform(v=>v||null),deliveryTerms:optional,paymentTerms:optional,note:optional,status:z.enum(["DRAFT","REVIEW_REQUESTED","APPROVED","SENT","CONTRACTED","CANCELED"]),items:z.string().transform((v,ctx)=>{try{return z.array(itemSchema).min(1,"품목을 한 개 이상 입력해 주세요.").parse(JSON.parse(v))}catch{ctx.addIssue({code:"custom",message:"견적 품목을 확인해 주세요."});return z.NEVER}})});

async function user(){const session=await auth();if(!session?.user?.id)throw new Error("로그인이 필요합니다.");return session.user;}
function values(form:FormData){return Object.fromEntries(form.entries())}
function message(error:unknown){if(error instanceof z.ZodError)return error.issues[0]?.message??"입력값을 확인해 주세요.";if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return "이미 등록된 고유 값입니다.";return error instanceof Error?error.message:"처리 중 오류가 발생했습니다."}
async function audit(userId:string,action:string,targetType:string,targetId:string,afterData?:object){await db.auditLog.create({data:{userId,action,targetType,targetId,afterData}})}
function go(path:string):never{redirect(path as Route)}
function fail(path:string,error:unknown):never{go(`${path}?error=${encodeURIComponent(message(error))}`)}
function isRedirect(error:unknown){return typeof error==="object"&&error!==null&&"digest" in error&&typeof error.digest==="string"&&error.digest.startsWith("NEXT_REDIRECT")}

export async function saveClient(form:FormData){const me=await user();const id=String(form.get("id")||"");try{const data=clientSchema.parse(values(form));const row=id?await db.client.update({where:{id},data}):await db.client.create({data:{...data,clientCode:`C-${Date.now()}`,clientType:"CUSTOMER",createdById:me.id}});await audit(me.id,id?"UPDATE":"CREATE","CLIENT",row.id);revalidatePath("/clients");go(`/clients/${row.id}?success=${encodeURIComponent("거래처가 저장되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail(id?`/clients/${id}`:"/clients/new",e)}}
export async function deleteClient(form:FormData){const me=await user();const id=String(form.get("id"));await db.client.update({where:{id},data:{deletedAt:new Date()}});await audit(me.id,"DELETE","CLIENT",id);revalidatePath("/clients");go("/clients?success="+encodeURIComponent("거래처가 삭제되었습니다."))}
export async function saveProduct(form:FormData){const me=await user();const id=String(form.get("id")||"");try{const data=productSchema.parse(values(form));const row=id?await db.product.update({where:{id},data}):await db.product.create({data});await audit(me.id,id?"UPDATE":"CREATE","PRODUCT",row.id);revalidatePath("/products");go("/products?success="+encodeURIComponent("품목이 저장되었습니다."))}catch(e){if(isRedirect(e))throw e;fail(id?`/products/${id}/edit`:"/products/new",e)}}
export async function deleteProduct(form:FormData){const me=await user();const id=String(form.get("id"));await db.product.update({where:{id},data:{deletedAt:new Date(),isActive:false}});await audit(me.id,"DELETE","PRODUCT",id);revalidatePath("/products")}

function calculateItems(items:z.infer<typeof itemSchema>[]) {return items.map((item,i)=>{const base=Math.round(item.quantity*item.unitPrice);const discount=Math.round(base*item.discountRate/100);const supplyAmount=base-discount;const vatAmount=item.taxType==="TAXABLE"?Math.round(supplyAmount*.1):0;return {...item,sortOrder:i+1,quantity:new Prisma.Decimal(item.quantity),unitPrice:item.unitPrice,supplyAmount,vatAmount,totalAmount:supplyAmount+vatAmount,discountRate:new Prisma.Decimal(item.discountRate)}})}
export async function saveQuotation(form:FormData){const me=await user();const id=String(form.get("id")||"");try{const parsed=quotationSchema.parse(values(form));const items=calculateItems(parsed.items);const subtotal=items.reduce((n,i)=>n+i.supplyAmount,0),vatAmount=items.reduce((n,i)=>n+i.vatAmount,0),discountAmount=parsed.items.reduce((n,i)=>n+Math.round(i.quantity*i.unitPrice*i.discountRate/100),0);const header={clientId:parsed.clientId,projectName:parsed.projectName,title:parsed.title,quotationDate:parsed.quotationDate,validUntil:parsed.validUntil,deliveryTerms:parsed.deliveryTerms,paymentTerms:parsed.paymentTerms,note:parsed.note,status:parsed.status as QuotationStatus,subtotal,discountAmount,taxableAmount:subtotal,vatAmount,totalAmount:subtotal+vatAmount};const row=await db.$transaction(async tx=>id?tx.quotation.update({where:{id},data:{...header,items:{deleteMany:{},create:items}}}):tx.quotation.create({data:{...header,quotationNumber:await nextDocumentNumber(tx,"quotation",parsed.quotationDate),revision:1,createdById:me.id,items:{create:items}}}));await audit(me.id,id?"UPDATE":"CREATE","QUOTATION",row.id);revalidatePath("/quotations");go(`/quotations/${row.id}?success=${encodeURIComponent("견적서가 저장되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail(id?`/quotations/${id}/edit`:"/quotations/new",e)}}
export async function deleteQuotation(form:FormData){const me=await user();const id=String(form.get("id"));await db.quotation.update({where:{id},data:{deletedAt:new Date()}});await audit(me.id,"DELETE","QUOTATION",id);revalidatePath("/quotations");go("/quotations")}
export async function copyQuotation(form:FormData){const me=await user();const id=String(form.get("id"));const source=await db.quotation.findUniqueOrThrow({where:{id},include:{items:true}});const row=await db.$transaction(async tx=>tx.quotation.create({data:{quotationNumber:await nextDocumentNumber(tx,"quotation",new Date()),revision:1,clientId:source.clientId,projectName:`${source.projectName} (복사본)`,title:source.title,quotationDate:new Date(),validUntil:source.validUntil,paymentTerms:source.paymentTerms,deliveryTerms:source.deliveryTerms,note:source.note,status:"DRAFT",subtotal:source.subtotal,discountAmount:source.discountAmount,taxableAmount:source.taxableAmount,vatAmount:source.vatAmount,totalAmount:source.totalAmount,createdById:me.id,items:{create:source.items.map(item=>({productId:item.productId,sortOrder:item.sortOrder,name:item.name,specification:item.specification,unit:item.unit,quantity:item.quantity,unitPrice:item.unitPrice,discountRate:item.discountRate,supplyAmount:item.supplyAmount,vatAmount:item.vatAmount,totalAmount:item.totalAmount,taxType:item.taxType,note:item.note}))}}}));await audit(me.id,"COPY","QUOTATION",row.id);revalidatePath("/quotations");go(`/quotations/${row.id}`)}
export async function convertQuotation(form:FormData){const me=await user();const id=String(form.get("id"));try{const q=await db.quotation.findFirstOrThrow({where:{id,deletedAt:null}});const row=await db.$transaction(async tx=>tx.project.create({data:{projectCode:await nextDocumentNumber(tx,"project",new Date()),projectName:q.projectName,clientId:q.clientId,quotationId:q.id,managerId:me.id,startDate:new Date(),contractAmount:q.totalAmount,budgetAmount:0,status:"CONTRACTED"}}));await db.quotation.update({where:{id},data:{status:"CONTRACTED"}});await audit(me.id,"CREATE_FROM_QUOTATION","PROJECT",row.id);revalidatePath("/projects");go(`/projects/${row.id}?success=${encodeURIComponent("프로젝트로 전환되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail(`/quotations/${id}`,e)}}

export async function saveProject(form:FormData){const me=await user();const id=String(form.get("id")||"");try{const data=projectSchema.parse(values(form));const row=id?await db.project.update({where:{id},data}):await db.$transaction(async tx=>tx.project.create({data:{...data,projectCode:await nextDocumentNumber(tx,"project",new Date())}}));await audit(me.id,id?"UPDATE":"CREATE","PROJECT",row.id);revalidatePath("/projects");go(`/projects/${row.id}?success=${encodeURIComponent("프로젝트가 저장되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail(id?`/projects/${id}/edit`:"/projects/new",e)}}
export async function saveExpense(form:FormData){const me=await user();const id=String(form.get("id")||"");try{const p=expenseSchema.parse(values(form));const supplyAmount=Math.round(p.quantity*p.unitPrice),vatAmount=p.taxable==="yes"?Math.round(supplyAmount*.1):0;const data={projectId:p.projectId,expenseCategoryId:p.expenseCategoryId,supplierId:p.supplierId,expenseDate:p.expenseDate,description:p.description,quantity:p.quantity,unitPrice:p.unitPrice,supplyAmount,vatAmount,totalAmount:supplyAmount+vatAmount,paymentMethod:p.paymentMethod,evidenceType:p.evidenceType,evidenceNumber:p.evidenceNumber,memo:p.memo};const row=id?await db.expense.update({where:{id},data}):await db.$transaction(async tx=>tx.expense.create({data:{...data,expenseNumber:await nextDocumentNumber(tx,"expense",p.expenseDate),status:"APPROVED",requestedById:me.id,approvedById:me.id,approvedAt:new Date()}}));await audit(me.id,id?"UPDATE":"CREATE","EXPENSE",row.id);revalidatePath("/expenses");revalidatePath(`/projects/${p.projectId}`);go(`/projects/${p.projectId}?success=${encodeURIComponent("비용이 저장되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail(id?`/expenses/${id}/edit`:"/expenses/new",e)}}
export async function deleteExpense(form:FormData){const me=await user();const id=String(form.get("id"));const row=await db.expense.update({where:{id},data:{deletedAt:new Date()}});await audit(me.id,"DELETE","EXPENSE",id);revalidatePath("/expenses");revalidatePath(`/projects/${row.projectId}`)}
export async function savePayment(form:FormData){const me=await user();try{const p=paymentSchema.parse(values(form));const project=await db.project.findUniqueOrThrow({where:{id:p.projectId}});const row=await db.$transaction(async tx=>tx.payment.create({data:{...p,clientId:project.clientId,paymentNumber:await nextDocumentNumber(tx,"payment",p.paymentDate),confirmedById:me.id}}));await audit(me.id,"CREATE","PAYMENT",row.id);revalidatePath("/payments");revalidatePath(`/projects/${p.projectId}`);go(`/projects/${p.projectId}?success=${encodeURIComponent("입금이 등록되었습니다.")}`)}catch(e){if(isRedirect(e))throw e;fail("/payments/new",e)}}
export async function deletePayment(form:FormData){const me=await user();const id=String(form.get("id"));const row=await db.payment.update({where:{id},data:{deletedAt:new Date()}});await audit(me.id,"DELETE","PAYMENT",id);revalidatePath("/payments");revalidatePath(`/projects/${row.projectId}`)}
